// <auto-generated />
namespace JobsApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class verifying : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(verifying));
        
        string IMigrationMetadata.Id
        {
            get { return "201611110429089_verifying.."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
